version: '2'

services:

# The Application
    app:
        container_name: laravel_app
        build:
            context: /usr/share/nginx/html/CYFood
            dockerfile: app.dockerfile
        volumes:
            - ./storage:/var/www/storage
        env_file: '.env.prod'
        environment:
            - "DB_HOST=database"
            - "REDIS_HOST=cache"

# The Web Server

    web:
        container_name: nginx_server
        build:
            context:  /usr/share/nginx/html/CYFood
            dockerfile: web.dockerfile
        volumes:
            - ./storage/logs/:/var/log/nginx
        ports:
            - 8990:80

# The Database

    database:
        container_name: mysql_database
        image: mariadb:10.2
        environment:
          - MYSQL_ROOT_PASSWORD=liean_sun
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 8991:3306

# redis

    cache:
        image: redis:3.0-alpine

volumes:
    dbdata:











